### ISSUE TITLE
training time consuming

### ISSUE THREAD

**Issue by cvtower** [DrImpossible/Deep-Expander-Networks#1]
Hello,

Nice work!
I noticed that all model mentioned in the original paper is trained on a platform containing 2 1080ti GPU. Since i do use the same HW, could you please share the training time consuming per epoch on imagenet, e.g.X-DenseNetBC-2-121. You know training imagenet is really too expensive compared to cifar database, and i have to consider this factor before training.

Appreciate your help!

**Comment by DrImpossible** [comment]
Hi!

I think it took me around 3-4 days to finish a run of X-DenseNetBC-2-121. Hope this helps!

**Comment by drimpossible** [comment]
Hi! It took me around 4300-4400 seconds for 1 training epoch, and ~60seconds for the eval using 2 GPUs and SSD for loading Imagenet. Hope it helps!
